// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using OtuGlazevTestDB.DataBase;

#nullable disable

namespace OtuGlazevTestDB.Migrations
{
    [DbContext(typeof(DataBaseContext))]
    [Migration("20230812181328_init")]
    partial class init
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
        }
    }
}
