using System;
using Microsoft.EntityFrameworkCore.Migrations;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace OtuGlazevTestDB.Migrations
{
    public partial class init : Migration
    {
        protected override void Up(MigrationBuilder migrationBuilder)
        {
            migrationBuilder.Sql(@"
CREATE TABLE public.""Users""
(
    id integer primary key GENERATED BY DEFAULT AS identity,
    ""firstName"" varchar(30),
    ""lastName"" varchar(30),
    ""dob"" date,
    ""creditScore"" int
    
);

CREATE TABLE public.""CreditTypes""
(
    id integer  PRIMARY KEY GENERATED BY DEFAULT AS identity,
    ""type"" varchar(30)
);

   
CREATE TABLE public.""Credits""
(
    ""id"" integer  PRIMARY key GENERATED BY DEFAULT AS identity,
    ""userId"" int,
    ""typeId"" int,
    ""debt"" int,
 	FOREIGN KEY (""userId"") REFERENCES ""Users""(""id"") ON DELETE cascade,
	FOREIGN KEY (""typeId"") REFERENCES ""CreditTypes""(""id"") ON DELETE cascade
);

insert  into public.""CreditTypes""(""type"") values('Car loan');
insert  into public.""CreditTypes""(""type"") values('Mortgage loan');
insert  into public.""CreditTypes""(""type"") values('Cash loan');
insert  into public.""CreditTypes""(""type"") values('Credit card');
insert  into public.""CreditTypes""(""type"") values('Pawnshop loan');


insert  into public.""Users""(""firstName"", ""lastName"", ""dob"", ""creditScore"") values('Andrey', 'Glazev', '14.01.2002','100');
insert  into public.""Users""(""firstName"", ""lastName"", ""dob"", ""creditScore"") values('Ivan', 'Ivanov', '24.01.2001', '82');
insert  into public.""Users""(""firstName"", ""lastName"", ""dob"", ""creditScore"") values('Andrey', 'Petrov', '17.05.2000', '23');
insert  into public.""Users""(""firstName"", ""lastName"", ""dob"", ""creditScore"") values('Kirill', 'Petrov', '14.05.1988', '34');
insert  into public.""Users""(""firstName"", ""lastName"", ""dob"", ""creditScore"") values('Sergey', 'Perfilov', '04.01.1972', '51');

insert  into public.""Credits""(""userId"", ""typeId"", ""debt"") values('1', '1', '10000');
insert  into public.""Credits""(""userId"", ""typeId"", ""debt"") values('2', '2',  '182000');
insert  into public.""Credits""(""userId"", ""typeId"", ""debt"") values('3', '3','300003');
insert  into public.""Credits""(""userId"", ""typeId"", ""debt"") values('4', '4', '540000');
insert  into public.""Credits""(""userId"", ""typeId"", ""debt"") values('5', '5', '510000');



");
        }

        protected override void Down(MigrationBuilder migrationBuilder)
        {
            migrationBuilder.DropTable(
                name: "Credits");

            migrationBuilder.DropTable(
                name: "CreditTypes");

            migrationBuilder.DropTable(
                name: "Users");
        }
    }
}
